# Generated by Django 5.2.4 on 2025-09-18 09:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crag",
            fields=[
                ("crag_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location_lat", models.FloatField()),
                ("location_lon", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=2083),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "crag",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "profile_picture",
                    models.URLField(blank=True, max_length=2083, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=2083),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deleted", "Deleted")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post",
                        to="MyApp.user",
                    ),
                ),
            ],
            options={
                "db_table": "post",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ClimbLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("route_name", models.CharField(blank=True, max_length=255, null=True)),
                ("date_climbed", models.DateField()),
                (
                    "difficulty_grade",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "crag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climb_logs",
                        to="MyApp.crag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climb_logs",
                        to="MyApp.user",
                    ),
                ),
            ],
            options={
                "db_table": "climb_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories_created",
                        to="MyApp.user",
                    ),
                ),
            ],
            options={
                "db_table": "category",
                "managed": True,
            },
        ),
    ]
