# Generated by Django 5.2.6 on 2025-09-21 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climblog',
            name='crag',
        ),
        migrations.RemoveField(
            model_name='climblog',
            name='difficulty_grade',
        ),
        migrations.RemoveField(
            model_name='climblog',
            name='route_name',
        ),
        migrations.AlterField(
            model_name='climblog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climb_log', to='MyApp.user'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=255)),
                ('route_grade', models.IntegerField()),
                ('route_type', models.CharField(choices=[('Boulder', 'Boulder'), ('Sport', 'Sport')], max_length=10)),
                ('crag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='MyApp.crag')),
            ],
        ),
        migrations.AddField(
            model_name='climblog',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climb_log', to='MyApp.route'),
        ),
    ]
