# Generated by Django 5.2.6 on 2025-10-01 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_crag_image_urls_alter_post_image_urls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='MyApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='MyApp.user')),
            ],
            options={
                'db_table': 'post_like',
                'managed': True,
                'indexes': [models.Index(fields=['post', 'user'], name='post_like_post_id_0fb066_idx')],
                'unique_together': {('post', 'user')},
            },
        ),
    ]
