# Generated by Django 5.2.6 on 2025-10-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_postlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
