# Generated by Django 5.2.6 on 2025-10-23 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_route_route_type_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crag',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='climblog',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climb_log', to='MyApp.route'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='MyApp.user'),
        ),
    ]
