# Generated by Django 5.2.6 on 2025-10-23 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_remove_crag_image_urls_remove_post_image_urls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CragModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('crag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crag_models', to='MyApp.crag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crag_models', to='MyApp.user')),
            ],
            options={
                'db_table': 'crag_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelRouteData',
            fields=[
                ('model_route_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_data', models.JSONField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_route_data', to='MyApp.cragmodel')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_route_data', to='MyApp.route')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_route_data', to='MyApp.user')),
            ],
            options={
                'db_table': 'model_route_data',
                'managed': True,
            },
        ),
    ]
