# Generated by Django 5.2.6 on 2025-10-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_cragmodel_modelroutedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='username',
        ),
    ]
