# Generated by Django 5.2.6 on 2025-10-27 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_rename_full_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='My_Title', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='MyApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='MyApp.user')),
            ],
            options={
                'db_table': 'post_comment',
                'managed': True,
                'indexes': [models.Index(fields=['post', 'user'], name='post_commen_post_id_989395_idx')],
            },
        ),
    ]
