# Generated by Django 5.2.4 on 2025-11-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cragmodel',
            name='name',
            field=models.CharField(null=True, unique=True),
        ),
    ]
