# Generated by Django 5.2.4 on 2025-11-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_cragmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='climblog',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='climblog',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='climblog',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
