# Generated by Django 5.2.4 on 2025-11-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_climblog_attempt_climblog_status_climblog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cragmodel',
            name='normalization_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
