# Generated by Django 5.2.4 on 2025-11-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_cragmodel_normalization_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cragmodel',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
