# Generated by Django 5.2.4 on 2025-11-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_alter_cragmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crags', to='MyApp.user'),
        ),
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='MyApp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
