# Generated by Django 5.2.4 on 2025-11-14 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_add_user_to_crag_and_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(db_index=True, help_text='Stripe PaymentIntent ID', max_length=255, unique=True)),
                ('amount', models.IntegerField(help_text='Amount in cents')),
                ('currency', models.CharField(default='sgd', max_length=3)),
                ('status', models.CharField(help_text='Payment status: succeeded, pending, failed, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When this payment was used for signup', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata from Stripe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='MyApp.user')),
            ],
            options={
                'db_table': 'user_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_intent_id'], name='user_paymen_payment_4408c6_idx'), models.Index(fields=['status'], name='user_paymen_status_43b82d_idx'), models.Index(fields=['created_at'], name='user_paymen_created_f4ddb6_idx')],
            },
        ),
    ]
